import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';

const items=[
 {title:'Variety of Pills',category:'Product visualization',file:'creatives/3d/Variety_of_Pills.glb',description:'A compact pharmaceutical collection prepared for fluid real-time presentation.',notes:'Converted from USDZ into an optimized GLB workflow, preserving the material hierarchy for browser rendering.',tech:['USDZ → GLB','Blender','Three.js']},
 {title:'Tablet Pill',category:'Hard-surface study',file:'creatives/3d/tablet-pill.glb',description:'A clean single-object study with a soft studio finish and inspectable geometry.',notes:'Imported from OBJ, normalized in Blender, materialized and exported as one portable binary asset for reliable web delivery.',tech:['OBJ → GLB','Material pass','WebGL']},
 {title:'Three Pill Boxes',category:'Packaging visualization',file:'creatives/3d/three-pill-boxes.glb',description:'A retail packaging set with embedded artwork and a product-ready presentation.',notes:'The highest-detail source was selected, textures were packed into the GLB, and the hierarchy was validated through a Blender re-import.',tech:['Texture packing','GLB validation','Blender']},
 {title:'Wheelchair',category:'Product visualization',file:'creatives/3d/wheelchair.glb',description:'A complex mechanical form made lightweight enough for interactive inspection.',notes:'Converted from the original Blender scene while retaining mesh groups and materials, then normalized dynamically for a consistent carousel scale.',tech:['BLEND → GLB','Scene cleanup','Three.js']},
 {title:'Spike Lug Nut',category:'Procedural modeling',file:'creatives/3d/spike_lug_nut_M14x1_5.glb',description:'A dimensioned automotive component modeled from reference imagery and engineering constraints.',notes:'Procedurally modeled at 119 × 23 mm with six terminated splines, a 60° conical seat, stepped collar detail and an M14×1.5 internal thread.',tech:['Procedural mesh','M14×1.5','Blender Python']}
];

const stage=document.querySelector('#modeling-lab-stage');
if(stage){
 const canvas=document.querySelector('#modeling-lab-canvas'),status=document.querySelector('#modeling-stage-status'),openBtn=document.querySelector('#modeling-open-button'),dragHint=document.querySelector('#modeling-drag-hint');
 const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(35,1,.01,100);camera.position.set(4.4,3,5.4);
 const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.enabled=false;controls.minDistance=3.4;controls.maxDistance=8;controls.target.set(0,.65,0);
 scene.add(new THREE.HemisphereLight(0xccecff,0x2d160c,2.4));const key=new THREE.DirectionalLight(0xffffff,4);key.position.set(4,6,4);scene.add(key);const rim=new THREE.DirectionalLight(0x00e0ff,3);rim.position.set(-5,3,-4);scene.add(rim);
 const floor=new THREE.Mesh(new THREE.CircleGeometry(3.5,64),new THREE.MeshStandardMaterial({color:0x11161a,roughness:.85,transparent:true,opacity:.8}));floor.rotation.x=-Math.PI/2;floor.position.y=-.78;scene.add(floor);
 const loader=new GLTFLoader();let boxScene,mixer,action,mount,demoProduct,currentProduct,index=0,state='loading',queuedIndex=null,pointerStart=null,boxMaterials=[];
 const setBoxOpacity=value=>boxMaterials.forEach(m=>{m.transparent=true;m.opacity=value;m.depthWrite=value>.35});
 function updateText(){const x=items[index];document.querySelector('#modeling-current-index').textContent=String(index+1).padStart(2,'0');document.querySelector('#modeling-category').textContent=x.category;document.querySelector('#modeling-title').textContent=x.title;document.querySelector('#modeling-description').textContent=x.description;document.querySelector('#modeling-note-number').textContent=`${String(index+1).padStart(2,'0')} — 05`;document.querySelector('#modeling-notes-text').textContent=x.notes;document.querySelector('#modeling-notes-tech').innerHTML=x.tech.map(t=>`<span>${t}</span>`).join('');document.querySelector('#modeling-progress-bar').style.transform=`scaleX(${index+1})`;document.querySelectorAll('#modeling-model-list button').forEach((b,i)=>b.setAttribute('aria-selected',i===index?'true':'false'))}
 function normalize(root){const b=new THREE.Box3().setFromObject(root),s=b.getSize(new THREE.Vector3()),c=b.getCenter(new THREE.Vector3()),scale=1.15/Math.max(s.x,s.y,s.z);root.position.sub(c).multiplyScalar(scale);root.scale.setScalar(scale)}
 function loadProduct(){state='loading';status.classList.remove('is-hidden');status.lastElementChild.textContent='Preparing '+items[index].title+'…';openBtn.classList.add('is-hidden');dragHint.classList.remove('is-visible');controls.enabled=false;if(currentProduct){mount.remove(currentProduct);currentProduct=null}loader.load(items[index].file,g=>{currentProduct=g.scene;normalize(currentProduct);mount.add(currentProduct);action.stop();action.reset();action.paused=true;setBoxOpacity(1);boxScene.visible=true;state='boxed';status.classList.add('is-hidden');openBtn.classList.remove('is-hidden')},undefined,()=>{status.lastElementChild.textContent='This model could not be loaded.'});updateText()}
 function openBox(){if(state!=='boxed')return;state='opening';openBtn.classList.add('is-hidden');action.reset();action.setLoop(THREE.LoopOnce,1);action.clampWhenFinished=true;action.timeScale=1;action.paused=false;action.play()}
 function select(next){if(next===index||state==='loading'||state==='reboxing')return;queuedIndex=(next+items.length)%items.length;openBtn.classList.add('is-hidden');dragHint.classList.remove('is-visible');controls.enabled=false;if(state==='boxed'){index=queuedIndex;queuedIndex=null;loadProduct();return}state='reboxing';boxScene.visible=true;setBoxOpacity(1);action.paused=false;action.timeScale=-1;if(action.time<=.01)action.time=action.getClip().duration;action.play()}
 function resize(){const r=stage.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(stage);resize();
 const list=document.querySelector('#modeling-model-list');items.forEach((x,i)=>{const b=document.createElement('button');b.type='button';b.role='tab';b.title=x.title;b.setAttribute('aria-label','Show '+x.title);b.addEventListener('click',()=>select(i));list.appendChild(b)});
 openBtn.addEventListener('click',openBox);document.querySelector('#modeling-prev').addEventListener('click',()=>select(index-1));document.querySelector('#modeling-next').addEventListener('click',()=>select(index+1));
 stage.addEventListener('pointerdown',e=>pointerStart={x:e.clientX,y:e.clientY});stage.addEventListener('pointerup',e=>{if(!pointerStart)return;const dx=e.clientX-pointerStart.x,dy=e.clientY-pointerStart.y;pointerStart=null;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.25)select(index+(dx<0?1:-1))});stage.addEventListener('keydown',e=>{if(e.key==='ArrowRight')select(index+1);if(e.key==='ArrowLeft')select(index-1);if((e.key==='Enter'||e.key===' ')&&state==='boxed')openBox()});
 loader.load('creatives/3d/amazon_box_product_reveal.glb',g=>{boxScene=g.scene;scene.add(boxScene);boxScene.rotation.y=-.22;mount=boxScene.getObjectByName('PRODUCT_ROOT');const demoNode=boxScene.getObjectByName('PRODUCT_NORMALIZE');demoProduct=demoNode?[demoNode]:[];demoProduct.forEach(o=>o.visible=false);boxScene.traverse(o=>{if(o.isMesh&&!demoProduct.some(d=>d===o||d.getObjectById(o.id))){const mats=Array.isArray(o.material)?o.material:[o.material];o.material=Array.isArray(o.material)?mats.map(m=>m.clone()):o.material.clone();(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>boxMaterials.push(m))}});mixer=new THREE.AnimationMixer(boxScene);action=mixer.clipAction(THREE.AnimationClip.findByName(g.animations,'BoxReveal')||g.animations[0]);mixer.addEventListener('finished',()=>{if(state==='opening'){state='revealed';controls.enabled=true;dragHint.classList.add('is-visible')}else if(state==='reboxing'){index=queuedIndex;queuedIndex=null;loadProduct()}});loadProduct()},undefined,()=>{status.lastElementChild.textContent='The animated box could not be loaded.'});
 let last=performance.now();function render(now){requestAnimationFrame(render);const dt=Math.min(.05,(now-last)/1000);last=now;if(mixer)mixer.update(dt);if(boxScene&&state==='boxed'){boxScene.rotation.y+=dt*.32;boxScene.position.y=Math.sin(now*.0017)*.035}if(action&&state==='opening'){const d=action.getClip().duration;if(action.time>d*.72)setBoxOpacity(Math.max(0,1-(action.time-d*.72)/(d*.25)))}if(state==='revealed'&&currentProduct)currentProduct.rotation.y+=dt*.12;controls.update();renderer.render(scene,camera)}requestAnimationFrame(render)
}
